apiVersion: v1
kind: Service
metadata:
  name: devops-info-service
spec:
  selector:
    app: devops-info-service
  ports:
    - port: 8000
      targetPort: 5000
      nodePort: 30080
      protocol: TCP
  type: NodePort