apiVersion: v1
kind: ConfigMap
metadata:
  name: version-env
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name | quote }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace | quote }}
data:
  MAJOR_VERSION: {{ .Values.version.major | quote }}
  MINOR_VERSION: {{ .Values.version.minor | quote }}
  PATCH_VERSION: {{ .Values.version.patch | quote }}