apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    organization: controlw
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        organization: controlw
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "myapp-role"
        vault.hashicorp.com/agent-inject-secret-credentials.txt: "secret/data/myapp"
    spec:
      serviceAccountName: myapp-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .Values.ports.container }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: version-env
          env:
            - name: APP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: username
            - name: APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: password
          resources:
            requests:
              memory: {{ .Values.resources.minimum.ram }}
              ephemeral-storage: {{ .Values.resources.minimum.disk }}
            limits:
              memory: {{ .Values.resources.maximum.ram }}
              ephemeral-storage: {{ .Values.resources.maximum.disk }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.endpoint }}
              port: {{ .Values.ports.container }}
            initialDelaySeconds: 5
            periodSeconds: {{ .Values.probes.readiness.period }}
            timeoutSeconds: 4
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.endpoint }}
              port: {{ .Values.ports.container }}
            initialDelaySeconds: 15
            periodSeconds: {{ .Values.probes.liveness.period }}
            timeoutSeconds: 4
            failureThreshold: 3