apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    organization: controlw
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        organization: controlw
    spec:
      volumes:
        - name: app-config
          configMap:
            name: {{ .Release.Name }}-config
        - name: app-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-data
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .Values.ports.container }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: version-env
          volumeMounts:
            - name: app-config
              mountPath: /config/config.json
              subPath: config.json
            - name: app-data
              mountPath: /data
          resources:
            requests:
              memory: {{ .Values.resources.minimum.ram }}
              ephemeral-storage: {{ .Values.resources.minimum.disk }}
            limits:
              memory: {{ .Values.resources.maximum.ram }}
              ephemeral-storage: {{ .Values.resources.maximum.disk }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.endpoint }}
              port: {{ .Values.ports.container }}
            initialDelaySeconds: 5
            periodSeconds: {{ .Values.probes.readiness.period }}
            timeoutSeconds: 4
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.endpoint }}
              port: {{ .Values.ports.container }}
            initialDelaySeconds: 15
            periodSeconds: {{ .Values.probes.liveness.period }}
            timeoutSeconds: 4
            failureThreshold: 3

  #strategy:
  #  canary:
  #    steps:
  #      - setWeight: 20
  #      - pause: {}
  #      - setWeight: 40
  #      - pause:
  #          duration: 30s
  #      - setWeight: 60
  #      - pause:
  #          duration: 30s
  #      - setWeight: 80
  #      - pause:
  #          duration: 30s
  #      - setWeight: 100

  strategy:
    blueGreen:
      activeService: {{ .Release.Name }}
      previewService: {{ .Release.Name }}-preview
      autoPromotionEnabled: false
      autoPromotionSeconds: 0
      scaleDownDelaySeconds: 0
