apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: {{ .Values.ports.internal }}
      targetPort: {{ .Values.ports.container }}
      nodePort: {{ .Values.ports.external }}
      protocol: TCP
  type: {{ .Values.service.type }}