name: lab-testing
on:
  push:
    branches: [ master, lab03 ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.10'

      - name: Install development dependencies
        run: |
          python -m venv venv
          pip install -r app_python/requirements-dev.txt

      - name: Run linter
        run: ruff check app_python/

      - name: Run unit tests
        run: pytest app_python/tests/

  release:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.base_ref == 'master'

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Read version
        id: version
        run: |
          echo "MAJOR_VERSION=$(grep '^MAJOR_VERSION=' app_python/version.env | cut -d '=' -f2-)" >> $GITHUB_OUTPUT
          echo "MINOR_VERSION=$(grep '^MINOR_VERSION=' app_python/version.env | cut -d '=' -f2-)" >> $GITHUB_OUTPUT
          echo "PATCH_VERSION=$(grep '^PATCH_VERSION=' app_python/version.env | cut -d '=' -f2-)" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            MAJOR_VERSION=${{ steps.version.outputs.MAJOR_VERSION }}
            MINOR_VERSION=${{ steps.version.outputs.MINOR_VERSION }}
            PATCH_VERSION=${{ steps.version.outputs.PATCH_VERSION }}
          tags: |
            controlw/devops-info-service:${{ steps.version.outputs.MAJOR_VERSION }}.${{ steps.version.outputs.MINOR_VERSION }}.${{ steps.version.outputs.PATCH_VERSION }}
            controlw/devops-info-service:latest
