name: lab-testing
on:
  push:
    branches: [ master, lab03 ]
  pull_request:
    branches: [ master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.10'

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: 0.10.5

      - name: Install development dependencies
        run: cd app_python && uv sync --dev --locked --no-install-project

      - name: Run linter
        run: cd app_python && uv run ruff check ./

      - name: Run unit tests
        run: cd app_python && uv run pytest tests/

      - name: Read version
        id: version
        run: |
          set -e

          MAJOR_VERSION=$(grep '^MAJOR_VERSION=' app_python/version.env | cut -d '=' -f2- | tr -d '\r')
          MINOR_VERSION=$(grep '^MINOR_VERSION=' app_python/version.env | cut -d '=' -f2- | tr -d '\r')
          PATCH_VERSION=$(grep '^PATCH_VERSION=' app_python/version.env | cut -d '=' -f2- | tr -d '\r')

          VERSION="${MAJOR_VERSION}.${MINOR_VERSION}.${PATCH_VERSION}"

          {
            echo "MAJOR_VERSION=$MAJOR_VERSION"
            echo "MINOR_VERSION=$MINOR_VERSION"
            echo "PATCH_VERSION=$PATCH_VERSION"
            echo "VERSION=$VERSION"
          } >> "$GITHUB_OUTPUT"

      - name: Build image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: app_python
          load: true
          build-args: |
            MAJOR_VERSION=${{ steps.version.outputs.MAJOR_VERSION }}
            MINOR_VERSION=${{ steps.version.outputs.MINOR_VERSION }}
            PATCH_VERSION=${{ steps.version.outputs.PATCH_VERSION }}
          tags: controlw/devops-info-service:${{ steps.version.outputs.VERSION }}

      - name: Scan the image with Snyk
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: controlw/devops-info-service:${{ steps.version.outputs.VERSION }}
          args: >-
            --severity-threshold=medium
            --fail-on=upgradable

  release:
    needs: validate
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.base_ref == 'master'

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Read version
        id: version
        run: |
          set -e
          MAJOR_VERSION=$(grep '^MAJOR_VERSION=' app_python/version.env | cut -d '=' -f2- | tr -d '\r')
          MINOR_VERSION=$(grep '^MINOR_VERSION=' app_python/version.env | cut -d '=' -f2- | tr -d '\r')
          PATCH_VERSION=$(grep '^PATCH_VERSION=' app_python/version.env | cut -d '=' -f2- | tr -d '\r')
          VERSION="${MAJOR_VERSION}.${MINOR_VERSION}.${PATCH_VERSION}"
          {
            echo "MAJOR_VERSION=$MAJOR_VERSION"
            echo "MINOR_VERSION=$MINOR_VERSION"
            echo "PATCH_VERSION=$PATCH_VERSION"
            echo "VERSION=$VERSION"
          } >> "$GITHUB_OUTPUT"
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: app_python
          push: true
          build-args: |
            MAJOR_VERSION=${{ steps.version.outputs.MAJOR_VERSION }}
            MINOR_VERSION=${{ steps.version.outputs.MINOR_VERSION }}
            PATCH_VERSION=${{ steps.version.outputs.PATCH_VERSION }}
          tags: >
            controlw/devops-info-service:${{ steps.version.outputs.VERSION }},
            controlw/devops-info-service:latest
